spring:
  application:
    name: posts-api
  datasource:
    url: jdbc:mysql://localhost:3306/posts?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update